version: "2"

services:
    auth:
        build: .
        image: fatzs:tag
        volumes:
            - ./api_rest:/app
        working_dir: /app
        environment:
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
        command: flask run --host=0.0.0.0
        ports:
            - 5000:5000
    


